.PHONY: clean All

All:
	@echo "----------Building project:[ tree_bfs - Debug ]----------"
	@cd "tree_bfs" && "$(MAKE)" -f  "tree_bfs.mk"
clean:
	@echo "----------Cleaning project:[ tree_bfs - Debug ]----------"
	@cd "tree_bfs" && "$(MAKE)" -f  "tree_bfs.mk" clean
